projects.yaml
Add ScalaJS category and some seed projects. Closes #44.
**Checklist:**
=> Add ScalaJS category

projects.yaml
Build tools are usually the first touch point with a language, users should get some guidance on what exists and is popular.
**Checklist:**
=> Add and fill section development-cycle

projects.yaml
Adding OpenAI Scala Client project.
**Checklist:**
=> Registering OpenAI Scala Client in projects.yaml

config/header.md
- Introduce Scala.js label
- Add clicks counter
Add clicks counter.
**Checklist:**
=> Add clicks counter

projects.yaml
A library to implement oauth2 on top of sttp
**Checklist:**
=> Add project: sttp-oauth2

projects.yaml
Introduced Scala.js tag as current option to indicate whether or not library is working with Scala.js
**Checklist:**
=> Introduce Scala.js label

projects.yaml
Mark ScalaJS compatible projects. Closes #43 
**Checklist:**
=> Mark ScalaJS compatible projects

projects.yaml
Apache Pekko is an open-source framework for building applications that are concurrent, distributed, resilient and elastic. Pekko is a fork of [Akka](https://github.com/akka/akka) 2.6.x, prior to the Akka project's adoption of the Business Source License.
**Checklist:**
=> Add project: pekko

projects.yaml
The Streaming-first HTTP server/module of Apache Pekko. Pekko HTTP is a fork of [Akka HTTP](https://github.com/akka/akka-http) 10.2.x release, prior to the Akka project's adoption of the Business Source License.
**Checklist:**
=> Add project: pekko-http

projects.yaml
Mark Scala 3 compatible libraries. Closes #42. 
**Checklist:**
=> Mark Scala 3 compatible libraries

projects.yaml
=> Standardize categories

projects.yaml
=> Add Logging category

projects.yaml
Spoiwo is an open-source library for functional-style spreadsheet generation in Scala. It was started as a wrapper over Apache POI and while the XLSX generation is still at its core, the library has been rectified to support number of other spreadsheet representations (including CSV and HTML).
**Checklist:**
=> Add project: spoiwo

projects.yaml
ZIO DynamoDB is a library that is used for type-safe, efficient, and boilerplate free access to AWS's DynamoDB service. It provides a type-safe API for many query types and the number of type-safe APIs is expanding.
**Checklist:**
=> Add project: zio-dynamodb

projects.yaml
Ox is a developer-friendly structured concurrency library for the JVM, based on:
* [Project Loom](https://openjdk.org/projects/loom/) (virtual threads)
* structured concurrency Java APIs ([JEP 428](https://openjdk.org/jeps/428)) 
* scoped values ([JEP 429](https://openjdk.org/jeps/429))
* [Go](https://golang.org)-like channels
* the [Scala 3](https://www.scala-lang.org) programming language
**Checklist:**
=> Add project: ox

projects.yaml
Snowplow is a developer-first engine for collecting behavioral data. In short, it allows you to:
- Collect events such as impressions, clicks, video playback (or even custom events of your choosing).
- Store the data in a scalable data warehouse you control ([Amazon Redshift](https://aws.amazon.com/redshift/), [Databricks](https://databricks.com/product/databricks-sql), [Elasticsearch](https://www.elastic.co/), [Google BigQuery](https://cloud.google.com/bigquery), [Snowflake](https://www.snowflake.com/workloads/data-warehouse-modernization/)) or emit it via a stream ([Amazon Kinesis](https://aws.amazon.com/kinesis/), [Google PubSub](https://cloud.google.com/pubsub/docs/overview), [Kafka](https://kafka.apache.org/)).
- …
=> Add project: Snowplow

projects.yaml
Remora from Zalando incubator. Kafka consumer lag-checking application for monitoring, written in Scala and Akka HTTP
**Checklist:**
=> Add remora

projects.yaml
=> Add sharaf, squery and tupson

projects.yaml
Add otavia :  Your shiny new IO & Actor programming model!
`Otavia` is an IO and Actor programming model power by `Scala 3`, it provides a toolkit to make writing high-performance concurrent programs more easily.
- Project at: [GitHub - otavia-projects/otavia](https://github.com/otavia-projects/otavia)
- Ecosystem at: [GitHub - otavia-projects](https://github.com/otavia-projects)
**Checklist:**
=> Add otavia : Your shiny new IO & Actor programming model! 

projects.yaml
Hi!
I would like to add a new database client project.
ldbc is Pure functional JDBC layer with Cats Effect 3 and Scala 3.
ldbc also offers a MySQL connector written in pure Scala3 as an experimental feature.
Project at: [GitHub - takapi327/ldbc](https://github.com/takapi327/ldbc)
Document at: https://takapi327.github.io/ldbc/
**Checklist:**
=> Add project: ldbc
